vai

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,11 +9,20 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Save .env as artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: env-file
-          path: .env
+      - name: Download .env file
+        run: |
+          if [ -f .env ]; then
+            cp .env .env
+            echo ".env file downloaded successfully"
+          else
+            echo ".env file not found"
+            exit 1
+          fi
+      # - name: Save .env as artifact
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: env-file
+      #     path: .env
 
   build:
     needs: prepare  # Depende do job 'prepare'
